### ISSUE TITLE
Error cuando la ruta del servicio está parametrizada

### ISSUE THREAD

**Issue by mgalbis-iti** [iti-ict/kukumo#20]
Cuando se indica una ruta con parámetros, por ejemplo, ```/service/{param1}/{param2}```, no puede crear la URI del servicio.

Ejemplo:
![image](https://user-images.githubusercontent.com/3009316/165925395-0461a2b6-f088-439a-8409-2d6e8d9b3ee0.png)
```
[ ERROR ]  Y se realiza la búsqueda (0.0) Illegal character in path at index 97: https://example.com/clientesFacturar/v1/{controlPJuridica}/{identificacionFiscal}/{tipoPJuridica}
stack trace:
iti.kukumo.api.KukumoException: Illegal character in path at index 97: https://example.com/clientesFacturar/v1/{controlPJuridica}/{identificacionFiscal}/{tipoPJuridica}
        at iti.kukumo.core.backend.RunnableStep.run(RunnableStep.java:123) ~[kukumo-core-1.3.1.jar:?]
        at iti.kukumo.core.backend.RunnableBackend.runStep(RunnableBackend.java:209) ~[kukumo-core-1.3.1.jar:?]
        at iti.kukumo.core.backend.RunnableBackend.runStep(RunnableBackend.java:82) ~[kukumo-core-1.3.1.jar:?]
        at iti.kukumo.core.runner.PlanNodeRunner.lambda$runStep$1(PlanNodeRunner.java:144) ~[kukumo-core-1.3.1.jar:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
```

Una posible solución sería dejar la ruta como string en lugar de convertirla a URI, ya que será RestAssured el que se encargará de comprobar que la ruta esté bien formada.

**Comment by linesta-iti** [comment]
¿Podrías indicar más datos relativos al error? Un ejemplo minimo reproducible, trazas del error, etc.
